name: campus_lost_found
description: Campus Lost & Found
publish_to: none
version: 0.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^8.0.0
  provider: ^6.0.0
  http: ^0.13.0
  image_picker: ^0.8.6
  flutter_secure_storage: ^6.0.0
  cached_network_image: ^3.2.3
  flutter_local_notifications: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
